---
- name: Install Collectd
  block:
    - name: Update Amazon Linux 2
      when: ansible_os_family == 'RedHat'
      yum:
        name: '*'
        state: latest

    - name: Updating Ubuntu
      block:
        - name: Release APT lock (Ubuntu only)
          command: "sudo rm -f /var/lib/apt/lists/lock /var/cache/apt/archives/lock /var/lib/dpkg/lock*"
          ignore_errors: yes
          changed_when: false

        - name: Configure dpkg (Ubuntu only)
          command: "sudo dpkg --configure -a"
          ignore_errors: yes
          changed_when: false

        - name: Update Ubuntu
          apt:
            upgrade: dist
            update_cache: yes
      when: ansible_os_family == 'Debian'

    - name: Update OS & Install Collectd
      package:
        name: "{{ 'collectd,collectd-write_prometheus' if ansible_os_family == 'RedHat' else 'collectd' }}"
        state: latest
      notify: Restart Collectd

    - name: Copy Prometheus Config Template
      template:
        src: prometheus.conf.j2
        dest: "{{ (ansible_os_family == 'RedHat') | ternary('/etc/collectd.d/prometheus.conf', '/etc/collectd/collectd.conf.d/prometheus.conf') }}"
      notify:
        - Restart Collectd
        - Test Collectd
  when: install_collectd | bool
