---
- name: Remove Collectd
  block:
    - name: Remove Config Files
      file:
        path: "{{ (ansible_os_family == 'RedHat') | ternary('/etc/collectd.d/prometheus.conf', '/etc/collectd/collectd.conf.d/prometheus.conf') }}"
        state: absent

    - name: Stop and Disable Collectd
      systemd:
        name: collectd
        state: stopped
        enabled: no

    - name: Remove Collectd and Plugins
      package:
        name: "{{ 'collectd,collectd-write_prometheus' if ansible_os_family == 'RedHat' else 'collectd' }}"
        state: absent
      async: 120  # 2 minutes
      poll: 0
      retries: 15
      delay: 10  # 10 seconds between retries


    - name: Clean cache & remove Collectd directory (Debian only)
      block:
        - name: Clean up APT cache (Debian only)
          apt:
            autoclean: yes
            autoremove: yes

        - name: Remove Collectd directory (Debian only)
          file:
            path: "/etc/collectd"
            state: absent
      when: ansible_os_family == 'Debian'
  when: not install_collectd | bool
