---
- name: Update Amazon Linux 2
  when: ansible_os_family == 'RedHat'
  yum:
    name: '*'
    state: latest

- name: Update Ubuntu
  when: ansible_os_family == 'Debian'
  apt:
    upgrade: dist
    update_cache: yes

- name: Install Required Packages
  package:
    name: "{{ item }}"
    state: latest
  with_items:
    - "{{ 'libsemanage-python,libselinux-python,selinux-policy' if ansible_distribution == 'Amazon' else 'python3-semanage,python3-selinux,policycoreutils,selinux-utils,selinux-basics' }}"
    - curl, lsof, mc, nano, tar, unzip, vim, zip
  when: install_required_packages | default(false) | bool
  register: install_pack

- name: Show Install Required Packages output
  debug:
    var: install_pack
